version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /opt/odoo/custom_addons/custom_addons:/mnt/custom_addons
      - /opt/odoo/config/odoo.conf:/etc/odoo/odoo.conf
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data:
